In [23]:
# Matrices are the R objects in which the elements are arranged in a two-dimensional rectangular layout.
# matrix(data, nrow, ncol, byrow, dimnames)
# byrow is a logical clue. If TRUE then the input vector elements are arranged by row.

# Elements are arranged sequentially by row.
M <- matrix(c(3:14), nrow = 4, byrow = TRUE)

print(M)

# eg 2 X 3 ( 2 by 3 Matrix)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [2]:
# Elements are arranged sequentially by row.
M2 <- matrix(c(3:14), nrow = 4, byrow = FALSE)

print(M2)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


In [3]:
# Define the column and row names.
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")
P <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(rownames, colnames))
print(P)


     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


In [6]:
# Access the element at 3rd column and 1st row.
print(P[1,3])

# Access the element at 2nd column and 4th row.
print(P[4,2])

# Access only the  2nd row.
print(P[2,])

# Access only the 3rd column.
print(P[,3])
#Note: If any field inside the bracket is left blank, it selects all.

print(P[])


[1] 5
[1] 13
col1 col2 col3 
   6    7    8 
row1 row2 row3 row4 
   5    8   11   14 
     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


In [7]:
#Addition
#Substitution

##Multiplication ( this require separate slide/ppt, more detail required for students. Elementwise, actual maths matrix)

# Matrix Multiplication & Division


In [17]:
m1 <- matrix(c(3:11), nrow = 3, byrow = FALSE)
m1

m2 <- matrix(c(3:11), nrow = 3, byrow = FALSE)
m2

mAdd <- m1+m2
mAdd

mminus <- m1-m2
mminus

mmulti <- m1*m2
mmulti
# Multiplication THIS concept is wrong, correct one need explanation !!


mDivide <- m1/m2
mDivide

# Inverse also special meaning

[,1] [,2] [,3]
[1,] 3    6     9  
[2,] 4    7    10  
[3,] 5    8    11

[,1] [,2] [,3]
[1,] 3    6     9  
[2,] 4    7    10  
[3,] 5    8    11

[,1] [,2] [,3]
[1,]  6   12   18  
[2,]  8   14   20  
[3,] 10   16   22

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

[,1] [,2] [,3]
[1,]  9   36    81 
[2,] 16   49   100 
[3,] 25   64   121

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1

In [18]:
print(attributes(P))


$dim
[1] 4 3

$dimnames
$dimnames[[1]]
[1] "row1" "row2" "row3" "row4"

$dimnames[[2]]
[1] "col1" "col2" "col3"




In [19]:
print(dim(P))


[1] 4 3


In [20]:
#creating a matrix is by using functions cbind() and rbind()

#First column, second column
mc <- cbind(c(1,2,3),c(4,5,6))
print(mc)

# First Row,second row

mr <- rbind(c(1,2,3),c(4,5,6))
print(mr)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [22]:
# Transpose

tpose <- t(mc)
tpose 

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

<font color="red">
two matrices can be multiplied only when the number of columns in the first equals the number of rows in the second
</font><p>
<font color="red">
No of columns in First == No of Rows in Second
</font>

In [24]:
# Row vector, column Vector, square Matrix

# Multiplication also called - DOT Matrix

# Inverse of matrix 1/m


In [27]:


Morig <- matrix(c(4,7,2,6), nrow = 2, byrow = TRUE)
Morig

[,1] [,2]
[1,] 4    7   
[2,] 2    6

In [29]:
print(solve(Morig))



print(det(Morig))

#det(Morig) != 0, so inverse exists


     [,1] [,2]
[1,]  0.6 -0.7
[2,] -0.2  0.4
[1] 10


In [32]:

M1 <- matrix(c(3,3.5,3.2,3.6), nrow = 2, byrow = TRUE)

M2 <- matrix(c(118.4,135.2), nrow = 1, byrow = TRUE)

M1
M2

[,1] [,2]
[1,] 3.0  3.5 
[2,] 3.2  3.6

[,1]  [,2] 
[1,] 118.4 135.2

In [33]:
minv = print(solve(M1))

     [,1]  [,2]
[1,]   -9  8.75
[2,]    8 -7.50


In [34]:
# x = BA-1  # Observe % ^ %
XResult <- M2 %*% minv 
XResult

[,1] [,2]
[1,] 16   22